let lessons = [
    {
        id: 1,
        subject:"Coding and Programming",
        description:"2 months programs of basics of Python, JavaScript, or HTML/CSS for kids.",
        location:"31 Jewry St, London EC3N 2ET",
        price: 15, 
        image:"images/image1.jpg",
        availablespaces: 10,
        rating: 5,  
    },
    {
        id: 2, 
        subject:"Music Lessons",
        description:"3 months suitable for kids who want to learn how to play guitar, piano, violin, or drum.",
        location:"Bigwood House, Henrietta Barnet School, Bigwood Rd, London NW11 7BD",
        price: 13, 
        image:"images/image2.jpg",
        availablespaces: 7, 
        rating: 4,
    },
    {
        id: 3, 
        subject:"Art Class",
        description:"1 month programs for children who like to draw & paint.",
        location:"Liberal Synagogue, 28 St John's Wood Rd, London NW8 7HA",
        price: 10, 
        image:"images/image3.png",
        availablespaces: 13,
        rating: 4, 
    },
    {
        id: 4, 
        subject:"Dance Class",
        description:"1 month for children who like to dance and stay fit.",
        location:"The Studio, Alexandra Palace, Alexandra Palace Way, London N22 7AY",
        price: 12, 
        image:"images/image4.jpg",
        availablespaces: 12,
        rating: 3, 
    },
    {
        id: 5, 
        subject:"Soccer",
        description:"Team training, drills, and match play for Kids.",
        location:"Fields, Tufnell Park Playing, Campdale Rd, London N7 0EB",
        price: 16, 
        image:"images/image5.jpeg",
        availablespaces: 20,
        rating: 5, 
    },
    {
        id: 6, 
        subject:"Cooking and Baking",
        description:"Simple, fun recipes for kids and teens.",
        location:"Bread Ahead Bakery School, Borough Market, London SE1 1TL",
        price: 25, 
        image:"images/image6.jpg",
        availablespaces: 8,
        rating: 3, 
    },
    {
        id: 7, 
        subject:"Digital Art Class",
        description:"2 months basic programs of digital illustration and graphic design for children.",
        location:"71 Cricklewood Broadway, London NW2 3JR",
        price: 15, 
        image:"images/image7.jpg",
        availablespaces: 10,
        rating: 4, 
    },
    {
        id: 8, 
        subject:"Swimming",
        description:"120 days of Swimming class for kids is designed to teach essential water safety and swimming skills in a fun, supportive, and safe environment.",
        location:"Angel Swim London Alderbook Primary School SW12 8PP",
        price: 13, 
        image:"images/image8.jpeg",
        availablespaces: 15,
        rating: 5, 
    },
    {
        id: 9, 
        subject:"Chess Club",
        description:"5 days of Strategy, critical thinking, and friendly Chess competition for children.",
        location:"Redcliffe Gardens, London SW10 9HF",
        price: 10, 
        image:"images/image9.jpeg",
        availablespaces: 20,
        rating: 4, 
    },
    {
        id: 10, 
        subject:"Gardening Club",
        description:"14 days of asics of planting and growing vegetables and flowers for kids.",
        location:"Park Building, 2 Newington Grn, Newington Green, London N1 4RF",
        price: 15, 
        image:"images/image10.jpg",
        availablespaces: 12,
        rating: 5, 
    },
]